#!/bin/bash

if [ -d "$JAVA_HOME/bin" ] ; then
  PATH="$JAVA_HOME/bin:$PATH"
fi

M2_HOME="$HOME/local/usr/maven/3.0.4"
if [ -d "$M2_HOME/bin" ] ; then
  export M2_HOME
  export M2="$M2_HOME/bin"
  PATH="$M2:$PATH"
fi

ANT_HOME="$HOME/local/usr/ant/current"
if [ -d "$ANT_HOME/bin" ] ; then
  export ANT_HOME
  PATH="$ANT_HOME/bin:$PATH"
fi

if [ -d "$HOME/node_modules/.bin" ] ; then
  PATH="$PATH:$HOME/node_modules/.bin"
fi

if [ -d "$HOME/local/usr/dart/dart-sdk/bin" ] ; then
  PATH="$PATH:$HOME/local/usr/dart/dart-sdk/bin"
fi

# set the go lang env
if [ -d "/usr/local/go" ] ; then
  export GOROOT="/usr/local/go"
  PATH="$PATH:$GOROOT/bin"
fi

if [ -d "$HOME/Projects/go" ] ; then
  export GOPATH="$HOME/Projects/go"
  PATH="$PATH:$GOPATH/bin"
fi

export PATH

export PS1='\u@\h:\w$(__git_ps1 " (%s)")\$ '
