# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = "[\ueab6](bold green)"
error_symbol = "[✗](bold red) "

[username]
format = "[$user]($style)"
detect_env_vars = ["STARSHIP_SHOW_PROMPT_DETAILS"]

[hostname]
format = "[@]($style)[$hostname]($style)[:]($style) "
detect_env_vars = ["STARSHIP_SHOW_PROMPT_DETAILS"]

[nodejs]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[line_break]
disabled = true

[directory]
home_symbol = "\uf015"

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[dart]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true
