# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character]
error_symbol = "[✗](bold red) "

[username]
format = "[$user]($style)"

[hostname]
format = "[@]($style)[$hostname]($style)[:]($style) "

[nodejs]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[line_break]
disabled = true

[directory]
home_symbol = "\uf015"

[package]
disabled = true

[ruby]
disabled = true
