[window]
opacity = 0.9
option_as_alt = "OnlyLeft"

[font]
normal.family = "SauceCodePro Nerd Font Mono"
bold.family = "SauceCodePro Nerd Font Mono"
italic.family = "SauceCodePro Nerd Font Mono"
bold_italic.family = "SauceCodePro Nerd Font Mono"

[keyboard]
bindings = [
  { key = "Up", mods = "Control|Shift|Option|Command", action = "ToggleMaximized" },
  { key = "Down", mods = "Control|Shift|Option|Command", action = "ToggleMaximized" }
]